WorldgenEvents.remove(event => {
    event.removeOres(props => {
      props.worldgenLayer = 'underground_ores';
      props.blocks = [
        "create:zinc_ore",
        "create:deepslate_zinc_ore",
        "create_dd:tin_ore",
        "occultism:silver_ore",
        "occultism:silver_ore_deepslate",
        "create_mew_age:thorium_ore",
        "minecraft:coal_ore",
        "minecraft:deepslate_coal_ore",
        "minecraft:copper_ore",
        "minecraft:deepslate_copper_ore",
        "minecraft:diamond_ore",
        "minecraft:deepslate_diamond_ore",
        "minecraft:emerald_ore",
        "minecraft:deepslate_emerald_ore",
        "minecraft:gold_ore",
        "minecraft:deepslate_gold_ore",
        "minecrawaft:iron_ore",
        "minecraft:deepslate_iron_ore",
        "minecraft:lapis_ore",
        "minecraft:deepslate_lapis_ore",
        "minecraft:nether_gold_ore",
        "minecraft:redstone_ore",
        "minecraft:deepslate_redstone_ore",
        "minecraft:ancient_debris",
        "minecraft:nether_quartz_ore",
        "treasure2:topaz_ore",
        "treasure2:ruby_ore",
        "treasure2:sapphire_ore",
        "treasure2:onyx_ore",
        "treasure2:deepslate_topaz_ore",
        "treasure2:deepslate_ruby_ore",
        "treasure2:deepslate_sapphire_ore",
        "treasure2:deepslate_onyx_ore",
        "bigreactors:yellorite_ore",
        "bigreactors:anglesite_ore",
        "bigreactors:benitoite_ore",
      ];
    });
  });