
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	[general.types]

		[general.types.wood_type]

			[general.types.wood_type.domum_ornamentum]
				cactus = true
				cactus_extra = true

			[general.types.wood_type.goodending]
				muddy_oak = true
				cypress = true

			[general.types.wood_type.biomesoplenty]
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.wood_type.ad_astra]
				aeronos = true
				strophar = true
				glacian = true

			[general.types.wood_type.treasure2]
				wither = true

			[general.types.wood_type.biomemakeover]
				blighted_balsa = true
				willow = true
				swamp_cypress = true
				ancient_oak = true

			[general.types.wood_type.gtceu]
				rubber = true

			[general.types.wood_type.alexscaves]
				pewen = true
				thornwood = true

			[general.types.wood_type.betterarcheology]
				rotten = true

			[general.types.wood_type.create_dd]
				rose = true
				smoked = true
				spirit = true
				rubber = true

			[general.types.wood_type.compressedblocks]
				c0_oak = true
				c1_oak = true
				c2_oak = true
				c3_oak = true
				c4_oak = true
				c5_oak = true
				c6_oak = true
				c7_oak = true
				c8_oak = true
				c9_oak = true
				c0_spruce = true
				c1_spruce = true
				c2_spruce = true
				c3_spruce = true
				c4_spruce = true
				c5_spruce = true
				c6_spruce = true
				c7_spruce = true
				c8_spruce = true
				c9_spruce = true
				c0_birch = true
				c1_birch = true
				c2_birch = true
				c3_birch = true
				c4_birch = true
				c5_birch = true
				c6_birch = true
				c7_birch = true
				c8_birch = true
				c9_birch = true
				c0_jungle = true
				c1_jungle = true
				c2_jungle = true
				c3_jungle = true
				c4_jungle = true
				c5_jungle = true
				c6_jungle = true
				c7_jungle = true
				c8_jungle = true
				c9_jungle = true
				c0_acacia = true
				c1_acacia = true
				c2_acacia = true
				c3_acacia = true
				c4_acacia = true
				c5_acacia = true
				c6_acacia = true
				c7_acacia = true
				c8_acacia = true
				c9_acacia = true
				c0_dark_oak = true
				c1_dark_oak = true
				c2_dark_oak = true
				c3_dark_oak = true
				c4_dark_oak = true
				c5_dark_oak = true
				c6_dark_oak = true
				c7_dark_oak = true
				c8_dark_oak = true
				c9_dark_oak = true
				c0_mangrove = true
				c1_mangrove = true
				c2_mangrove = true
				c3_mangrove = true
				c4_mangrove = true
				c5_mangrove = true
				c6_mangrove = true
				c7_mangrove = true
				c8_mangrove = true
				c9_mangrove = true
				c0_cherry = true
				c1_cherry = true
				c2_cherry = true
				c3_cherry = true
				c4_cherry = true
				c5_cherry = true
				c6_cherry = true
				c7_cherry = true
				c8_cherry = true
				c9_cherry = true

		[general.types.leaves_type]

			[general.types.leaves_type.biomesoplenty]
				origin = true
				flowering_oak = true
				maple = true
				orange_autumn = true
				yellow_autumn = true
				rainbow_birch = true
				snowblossom = true
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.leaves_type.goodending]
				cypress = true
				dense_birch = true
				dense_dark_oak = true

			[general.types.leaves_type.croptopia]
				cinnamon = true

			[general.types.leaves_type.ad_astra]
				glacian = true

			[general.types.leaves_type.chipped]
				apple_acacia = true
				cherry_acacia = true
				dead_acacia = true
				frosted_acacia = true
				golden_acacia = true
				golden_apple_acacia = true
				golden_cherry_acacia = true
				magenta_flower_acacia = true
				orange_acacia = true
				red_acacia = true
				white_flower_acacia = true
				apple_birch = true
				cherry_birch = true
				dead_birch = true
				frosted_birch = true
				golden_birch = true
				golden_apple_birch = true
				golden_cherry_birch = true
				magenta_flower_birch = true
				orange_birch = true
				red_birch = true
				white_flower_birch = true
				apple_dark_oak = true
				cherry_dark_oak = true
				dead_dark_oak = true
				frosted_dark_oak = true
				golden_dark_oak = true
				golden_apple_dark_oak = true
				golden_cherry_dark_oak = true
				magenta_flower_dark_oak = true
				orange_dark_oak = true
				red_dark_oak = true
				white_flower_dark_oak = true
				apple_jungle = true
				cherry_jungle = true
				dead_jungle = true
				frosted_jungle = true
				golden_jungle = true
				golden_apple_jungle = true
				golden_cherry_jungle = true
				magenta_flower_jungle = true
				orange_jungle = true
				red_jungle = true
				white_flower_jungle = true
				apple_oak = true
				cherry_oak = true
				dead_oak = true
				frosted_oak = true
				golden_oak = true
				golden_apple_oak = true
				golden_cherry_oak = true
				magenta_flower_oak = true
				orange_oak = true
				red_oak = true
				white_flower_oak = true
				apple_spruce = true
				cherry_spruce = true
				dead_spruce = true
				frosted_spruce = true
				golden_spruce = true
				golden_apple_spruce = true
				golden_cherry_spruce = true
				magenta_flower_spruce = true
				orange_spruce = true
				red_spruce = true
				white_flower_spruce = true

			[general.types.leaves_type.biomemakeover]
				blighted_balsa = true
				willow = true
				swamp_cypress = true
				ancient_oak = true

			[general.types.leaves_type.gtceu]
				rubber = true

			[general.types.leaves_type.alexscaves]
				ancient = true

			[general.types.leaves_type.create_dd]
				rubber = true

	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.chipped]
				fine_planks = true
				checkered_trapdoor = true
				overgrown_trapdoor = true
				overgrown_door = true
				windowed_door = true
				tiled_door = true
				classic_trapdoor = true
				circle_glass = true
				pegged_planks = true
				torch = true
				secret_door = true
				smooth_planks = true
				screen_door = true
				bared_glass = true
				ornate_bared_glass = true
				hewn_planks = true
				crossed_planks = true
				beach_door = true
				fine_vertical_planks = true
				cross_laced_planks = true
				diamond_bordered_glass = true
				railed_planks = true
				planks_mosaic = true
				distorted_trapdoor = true
				iron_barred_trapdoor = true
				circle_glass_pane = true
				versailles_planks = true
				whirlwind_planks = true
				large_diamond_glass_pane = true
				framed_planks = true
				square_glass = true
				vined_trapdoor = true
				barrel = true
				woven_glass = true
				detailed_planks = true
				woven_trapdoor = true
				cobweb_trapdoor = true
				gated_door = true
				supported_door = true
				barred_trapdoor = true
				line_bared_glass_pane = true
				horizontal_lined_glass_pane = true
				airy_trapdoor = true
				line_bared_glass = true
				slanted_planks = true
				barred_door = true
				suspicious_trapdoor = true
				herringbone_planks = true
				pressed_door = true
				planks_panel = true
				vertically_railed_planks = true
				bared_glass_pane = true
				diamond_bordered_glass_pane = true
				solid_trapdoor = true
				tiled_planks = true
				boarded_door = true
				dual_paneled_door = true
				square_glass_pane = true
				meshed_trapdoor = true
				thin_planks = true
				fancy_trapdoor = true
				paper_door = true
				warted_trapdoor = true
				basket_woven_planks = true
				enclosed_planks = true
				double_herringbone_planks = true
				crated_planks = true
				horizontal_lined_glass = true
				natural_planks = true
				classic_windowed_trapdoor = true
				brick_bond_planks = true
				wickered_planks = true
				bordered_glass_pane = true
				sliding_door = true
				heavy_trapdoor = true
				bordered_glass = true
				laced_planks = true
				boxed_planks = true
				reinforced_crate = true
				large_diamond_glass = true
				snowflake_glass_pane = true
				bricky_planks = true
				slotted_trapdoor = true
				shack_door = true
				polished_planks = true
				ornate_bared_glass_pane = true
				diagonal_planks = true
				wall_torch = true
				crate = true
				nailed_planks = true
				cornered_planks = true
				shifted_planks = true
				vertical_planks = true
				glass_door = true
				fortified_door = true
				paneled_door = true
				leafy_trapdoor = true
				snowflake_glass = true
				heavy_door = true
				pointless_trapdoor = true
				stacked_planks = true
				planks_shavings = true
				twisted_trapdoor = true
				diamond_planks = true
				woven_glass_pane = true
				windowed_trapdoor = true
				tile_windowed_door = true
				golden_barred_trapdoor = true

			[general.entries.wood_type.farmersdelight]
				cabinet = true

			[general.entries.wood_type.create]
				window_pane = true
				window = true

			[general.entries.wood_type.friendsandfoes]
				beehive = true

